kumuluzee:
  name: code-outputs
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/OutputMetadataPS
      connection-url: jdbc:postgresql://localhost:5431/code-outputs
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/OutputMetadataPS
      etcd-health-check:
        connection-url: http://localhost:2379/health
  metrics:
    web-instrumentation:
      - name: outputs-endpoint
        url-pattern: /v1/outputs/*
app-config:
  external-services:
    enabled: true
  jdoodle:
    client-id: 336e764a0d15862c64c12304e1d90687
    secret-key: a886859dc6d68b2744c1b434ad7c4ceb3611f5877a905a05e5f7375665f40a73