kumuluzee:
  name: code-outputs
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/OutputMetadataPS
      connection-url: jdbc:postgresql://localhost:5431/code-outputs
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/OutputMetadataPS
      etcd-health-check:
        connection-url: http://etcd:2379/health
  metrics:
    web-instrumentation:
      - name: outputs-endpoint
        url-pattern: /v1/outputs/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                           <Configuration name="outputs">
                               <Appenders>
                                   <Console name="console" target="SYSTEM_OUT">
                                       <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                   </Console>
                                   <Socket name="logstash" host="7d264c39-0e8a-4a2b-b850-db059d5fdb1b-ls.logit.io"
                                   port="11963" protocol="tcp">
                                       <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                   </Socket>
                               </Appenders>
                               <Loggers>
                                   <!-- Default logger -->
                                   <Root level="all">
                                       <AppenderRef ref="console" level="info"/>
                                       <AppenderRef ref="logstash" level="trace"/>
                                   </Root>
                               </Loggers>
                           </Configuration>'
app-config:
  external-services:
    enabled: true
  jdoodle:
    client-id: 336e764a0d15862c64c12304e1d90687
    secret-key: a886859dc6d68b2744c1b434ad7c4ceb3611f5877a905a05e5f7375665f40a73
