kumuluzee:
  name: code-outputs
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/OutputMetadataPS
      connection-url: jdbc:postgresql://localhost:5431/exercise-metadata
      username: dbuser
      password: postgres
      max-pool-size: 20