kumuluzee:
  name: code-outputs
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/OutputMetadataPS
      connection-url: jdbc:postgresql://localhost:5431/code-outputs
      username: dbuser
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/OutputMetadataPS
  metrics:
    web-instrumentation:
      - name: outputs-endpoint
        url-pattern: /v1/outputs/*
