kumuluzee:
  name: code-outputs
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/OutputMetadataPS
      connection-url: jdbc:postgresql://localhost:5431/code-outputs
      username: dbuser
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://localhost:2379
